exclude_files = {
    ".luacheckrc",
    "Tests/",
    "Libs/",
}

-- https://luacheck.readthedocs.io/en/stable/warnings.html

ignore = {
    "11./BINDING_.*", -- Setting an undefined (Keybinding) global variable
    "211", -- Unused local variable
    "212", -- Unused argument
    "213", -- Unused loop variable
    "432/self", -- Shadowing a local variable
    "542", -- empty if branch
    "631", -- line too long
}

globals = {
    "LiteButtonAurasController",
    "LiteButtonAurasControllerMixin",
    "LiteButtonAurasDB",
    "LiteButtonAurasOverlayMixin",
    "LiteButtonAuras_AddonCompartmentFunc",
    "SlashCmdList",
}

read_globals =  {
    "ABP_NS",
    "ActionBarActionButtonMixin",
    "ActionBarButtonEventsFrame",
    "ActionButton_HideOverlayGlow",
    "ActionButton_SetupOverlayGlow",
    "ActionButton_Update",
    "ActionButtonSpellAlertManager",
    "ADD",
    "AuraUtil",
    "C_ActionBar",
    "C_Item",
    "C_Spell",
    "C_SpellBook",
    "C_UnitAuras",
    "ChatFontNormal",
    "ContinuableContainer",
    "CopyTable",
    "CreateFrame",
    "CreateFromMixins",
    "DebuffTypeColor",
    "DEFAULT",
    "DELETE",
    "Dominos",
    "format",
    "GameFontHighlight",
    "GameFontNormal",
    "GAMEMENU_HELP",
    "GameTooltip_Hide",
    "GameTooltip",
    "GENERAL",
    "GetActionInfo",
    "GetActionText",
    "GetCVarBool",
    "GetKeysArray",
    "GetLocale",
    "GetMacroBody",
    "GetMacroIndexByName",
    "GetMacroItem",
    "GetMacroSpell",
    "GetModifiedClick",
    "GetNumArenaOpponents",
    "GetNumGroupMembers",
    "GetTime",
    "GetTotemInfo",
    "GetValuesArray",
    "GetWeaponEnchantInfo",
    "GRAY_FONT_COLOR",
    "HasAction",
    "HIGHLIGHT_FONT_COLOR",
    "hooksecurefunc",
    "IsModifiedClick",
    "IsMouseButtonDown",
    "IsPlayerSpell",
    "IsSpellOverlayed",
    "LE_EXPANSION_LEVEL_CURRENT",
    "LibStub",
    "MAX_BOSS_FRAMES",
    "MAX_TOTEMS",
    "Mixin",
    "NONE",
    "NORMAL_FONT_COLOR",
    "NumberFontNormal",
    "OKAY",
    "ORANGE_FONT_COLOR",
    "PixelUtil",
    "PLAYER",
    "REMOVE",
    "SecureCmdOptionParse",
    "SELECTED_CHAT_FRAME",
    "Settings",
    "SETTINGS",
    "sort",
    "Spell",
    "SPELLS",
    "strsplit",
    "table",
    "TARGET",
    "tContains",
    "tDeleteItem",
    "UIParent",
    "UnitCanAttack",
    "UnitCastingInfo",
    "UnitChannelInfo",
    "UnitExists",
    "UnitIsFriend",
    "UnitIsUnit",
    "WithinRange",
    "WOW_PROJECT_CLASSIC",
    "WOW_PROJECT_ID",
}
